import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import {Book} from '../models/Book';


@Injectable({
  providedIn: 'root'
})
export class BooksService {
  books: Book[] = [
    {
      id: '7e9342a0-6886-4410-9145-237fb871b999',
      name: 'Generate UIID',
      description: 'he UUIDs generated by this site are provided AS IS without warranty of any kind, not even the warranty ' +
        'that the generated UUIDs are actually unique. You are responsible for using the UUIDs and assume any risk inherent ' +
        'to using them. You are not permitted to use the UUIDs generated by this site if you do not agree to these terms.' +
        ' Do not use any UUIDs found on cached versions of this page.',
      author: 'Jhon Harvi',
      link: [
        {
          type: 'epub',
          link: 'link1',
        },
        {
          type: 'pdf',
          link: 'link2'
        },
      ],
    },
  ];
  constructor() { }
  getBooks() {
    return of(this.books);
  }
  getBookById(id: string) {
    const book = this.books.find( iteratorBook => iteratorBook.id === id);
    return of(book);
  }
  addBook(book: Book) {

  }
  editBook(book: Book) {
    this.books = this.books.map(item => {
      if (book.id === item.id) {
        item = book;
      }
      return item;
    });
    return of(book);
  }
  deleteBook(id: string) {

  }
}
